# vim : ft=conf  #

[[plugins]]
repo =  'vim-scripts/jcommenter.vim'
on_ft = ['c','java','verilog','systemverilog','verilog_systemverilog']
hook_post_update='''
tabnew plugin/jcommenter.vim
set ff=unix
w
bd
'''

[[plugins]]
repo =  'scrooloose/syntastic'
on_ft = ['c','verilog','systemverilog','verilog_systemverilog']
hook_add='''
let g:syntastic_verilog_systemverilog_checkers=['verilator']
'''

#Table Mode
[[plugins]]
repo =  'dhruvasagar/vim-table-mode'
on_ft=['markdown']

[[plugins]]
repo = 't9md/vim-quickhl'
hook_add='''
    nmap <Space>h <Plug>(quickhl-manual-this)
    xmap <Space>h <Plug>(quickhl-manual-this)
    nmap <Space>H <Plug>(quickhl-manual-reset)
    xmap <Space>H <Plug>(quickhl-manual-reset)
    let g:quickhl_manual_colors = [
      \ "gui=bold ctermfg=16   ctermbg=1   guifg=#ffffff guibg=#0a7383",
      \ "gui=bold ctermfg=000   ctermbg=3   guibg=#a07040 guifg=#ffffff",
      \ "gui=bold ctermfg=16   ctermbg=5   guibg=#4070a0 guifg=#ffffff",
      \ "gui=bold ctermfg=000   ctermbg=6   guibg=#40a070 guifg=#ffffff",
      \ "gui=bold ctermfg=16   ctermbg=4   guibg=#40a070 guifg=#ffffff",
      \ ]
'''

#######################################################
#Unite
#######################################################

#Neomru
[[plugins]]
repo = 'Shougo/neomru.vim'
hook_post_source='''
let g:neomru#file_mru_ignore_pattern = substitute(g:neomru#directory_mru_ignore_pattern,"/mnt/\\\\|","","g")
'''

[[plugins]]
repo='Shougo/unite.vim'
depends='neomru.vim'
hook_add='''
    nnoremap <silent> <Leader>ab :UniteBookmarkAdd<CR>
    nnoremap <silent> <Leader>b :Unite bookmark<CR>
    nnoremap <silent> <Leader>bb :Unite bookmark<CR>
'''

#"VimFiler
[[plugins]]
repo = 'Shougo/vimfiler'
depends='unite.vim'

[[plugins]]
repo = 'Shougo/defx.nvim'

#############
# Denite
############
[[plugins]]
repo = 'Shougo/denite.nvim'
depends = 'neomru.vim'
# Key Bind Setting 
hook_post_source='''
nnoremap <Leader>uu :Denite file_mru<CR>
nnoremap <Leader>uf :Denite file<CR>

call denite#custom#option('default','direction','top')
call denite#custom#option('default','mode','normal')

"denite/insert モードのときは，C- で移動できるようにする
call denite#custom#map('insert', "<C-j>", '<denite:move_to_next_line>')
call denite#custom#map('insert', "<C-k>", '<denite:move_to_previous_line>')

"tabopen や vsplit のキーバインドを割り当て
call denite#custom#map('insert', "<C-t>", '<denite:do_action:tabopen>')
call denite#custom#map('insert', "<C-v>", '<denite:do_action:vsplit>')
call denite#custom#map('normal', "v", '<denite:do_action:vsplit>')

"jj -> denite/insert を抜けるようにする
call denite#custom#map('insert', 'jj', '<denite:enter_mode:normal>')

autocmd FileType denite call s:denite_my_settings()
function! s:denite_my_settings() abort
nnoremap <silent><buffer><expr> <CR>
\ denite#do_map('do_action')
nnoremap <silent><buffer><expr> d
\ denite#do_map('do_action', 'delete')
nnoremap <silent><buffer><expr> p
\ denite#do_map('do_action', 'preview')
nnoremap <silent><buffer><expr> q
\ denite#do_map('quit')
nnoremap <silent><buffer><expr> i
\ denite#do_map('open_filter_buffer')
nnoremap <silent><buffer><expr> <Space>
\ denite#do_map('toggle_select').'j'
endfunction

'''

#call unite#custom_default_action('source/bookmark/directory' , 'cd')

#"VimFiler
[[plugins]]
repo = 'Shougo/vimfiler'
depends='unite.vim'


#[[plugins]]
#repo =  'Shougo/vimshell.vim'
#
#"NeoSnippet
[[plugins]]
repo = 'Shougo/neosnippet'
depends = ['neosnippet-snippets']
on_i = 1
hook_add='''
let g:neosnippet#snippets_directory='~/.dotfiles/vim/snippets/'
'''


#
####################
# C
####################
[[plugins]]
repo =  'vim-scripts/taglist.vim'
on_ft = ['c','verilog','systemverilog','verilog_systemverilog','vb']

#[[plugins]]
#repo='inkarkat/vim-SyntaxRange'

