#Table Mode
[[plugins]]
repo =  'dhruvasagar/vim-table-mode'
on_ft=['markdown']

#call unite#custom_default_action('source/bookmark/directory' , 'cd')

#[[plugins]]
#repo =  'Shougo/vimshell.vim'
#[[plugins]]
#repo =  't9md/vim-choosewin'
#
#"NeoSnippet
#[[plugins]]
#repo =  'Shougo/neosnippet.vim'
#[[plugins]]
#repo =  'Shougo/neosnippet-snippets'
#
#Git
[[plugins]]
repo =  'tpope/vim-fugitive'
hook_add='''
set statusline=%F%m%r%h%w\ %=%{fugitive#statusline()}\ \ [%Y,%{&ff}]\ [POS=%04l,%04v][%p%%]\ [LEN=%L]
'''

[[plugins]]
repo =  'gregsexton/gitv'

