[[plugins]]
repo =  'scrooloose/syntastic'
on_ft = ['c','verilog','systemverilog']

##Verilog
#[[plugins]]
#repo =  "vhda/verilog_systemverilog.vim"
#on_ft=

#Table Mode
[[plugins]]
repo =  'dhruvasagar/vim-table-mode'
on_ft=['markdown']

#call unite#custom_default_action('source/bookmark/directory' , 'cd')

#[[plugins]]
#repo =  'Shougo/vimshell.vim'
#
#"NeoSnippet
#[[plugins]]
#repo =  'Shougo/neosnippet.vim'
#[[plugins]]
#repo =  'Shougo/neosnippet-snippets'
#
####################
# C
####################
[[plugins]]
repo =  'vim-scripts/taglist.vim'
on_ft=['c']

###############
# Git
###############
[[plugins]]
repo =  'rhysd/committia.vim'

[[plugins]]
repo ='tpope/vim-fugitive'
depends='committia.vim'
hook_add='''
    set statusline=%F%m%r%h%w\ %=%{fugitive#statusline()}\ \ [%Y,%{&ff}]\ [POS=%04l,%04v][%p%%]\ [LEN=%L]
'''

[[plugins]]
repo =  'gregsexton/gitv'
depends='vim-fugitive'

#[[plugins]]
#repo =  'cohama/agit.vim'

