# 基本は github.com のレポジトリーを指定するだけ
[[plugins]]
repo = 'Shougo/dein.vim'

# git clone 後、実行すべきコマンドがある場合はこんな感じ
[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
elseif executable('gmake')
    let cmd = 'gmake'
else
    let cmd = "echo vimproc: make &&"
    let cmd = cmd.'make'
endif
    let g:dein#plugin.build = cmd
'''
#elseif dein#util#_is_cygwin()
#    let cmd = 'make -f make_cygwin.mak'
#elseif executable('gmake')
#    let cmd = 'gmake'
#else
#    let cmd = 'make'
#endif
#    echo "vimproc: cygwin"
#    echo "vimproc: windows"
#    echo "vimproc: gmake"

#Color Scheme
[[plugins]]
repo =  'sjl/badwolf'
[[plugins]]
repo =  'vim-scripts/baycomb'
[[plugins]]
repo =  "w0ng/vim-hybrid"
[[plugins]]
repo =  'altercation/vim-colors-solarized'

#NeoComplete
[[plugins]]
repo =  'Shougo/neocomplete'
[[plugins]]
repo =  'Shougo/neocomplcache'

##Denite
#[[plugins]]
#repo = 'Shougo/denite.nvim'

#"[[plugins]]
#"repo =  'idanarye/vim-merginal'
#"[[plugins]]
#"repo =  'cohama/agit.vim'
#"[[plugins]]
#"repo =  'rhysd/committia.vim'
#[[plugins]]
#repo =  'gregsexton/gitv'
#
#Align
[[plugins]]
repo =  'vim-scripts/Align'

#[[plugins]]
#repo =  'changed'
#[[plugins]]
#repo =  'vim-scripts/BlockDiff'
#[[plugins]]
#repo =  'vim-scripts/ifdef.vim'
#
#"VimTex
#[[plugins]]
#repo =  'lervag/vimtex'
#
#[[plugins]]
#repo =  'LeafCage/foldCC.vim'
#
#[[plugins]]
#repo =  'tpope/vim-surround'
#
#[[plugins]]
#repo =  'thinca/vim-quickrun'
#
#[[plugins]]
#repo =  'scrooloose/syntastic'
#[[plugins]]
#repo =  'vim-scripts/taglist.vim'
#
#[[plugins]]
#repo =  'wannesm/wmgraphviz.vim'
#
#"Verilog
#[[plugins]]
#repo =  "vhda/verilog_systemverilog.vim"
#
#
#"Markdown
#[[plugins]]
#repo =  'plasticboy/vim-markdown'
#[[plugins]]
#repo =  'kannokanno/previm'
#[[plugins]]
#repo =  'tyru/open-browser.vim'
#
#"GDB
#"[[plugins]]
#"repo =  'vim-scripts/Conque-GDB'
#
#"TMUX
[[plugins]]
repo =  'christoomey/vim-tmux-navigator'

#"VimDiff by histogram
#[[plugins]]
#repo =  'lambdalisue/vim-unified-diff'
#[[plugins]]
#repo =  'chrisbra/vim-diff-enhanced'
#
#"Calendar
#[[plugins]]
#repo =  'itchyny/calendar.vim'
#
#"DiffChar
#"[[plugins]]
#"repo =  'vim-scripts/diffchar.vim'
#
