# vim : ft=conf  #

[[plugins]]
repo =  'vim-scripts/jcommenter.vim'
on_ft = ['c','java','verilog','systemverilog','verilog_systemverilog']

[[plugins]]
repo =  'scrooloose/syntastic'
on_ft = ['c','verilog','systemverilog','verilog_systemverilog']

#Table Mode
[[plugins]]
repo =  'dhruvasagar/vim-table-mode'
on_ft=['markdown']

#call unite#custom_default_action('source/bookmark/directory' , 'cd')

#[[plugins]]
#repo =  'Shougo/vimshell.vim'
#
#"NeoSnippet
[[plugins]]
repo = 'Shougo/neosnippet'
depends = ['neosnippet-snippets']
on_i = 1
hook_add='''
let g:neosnippet#snippets_directory='~/.dotfiles/vim/snippets/'
'''


#
####################
# C
####################
[[plugins]]
repo =  'vim-scripts/taglist.vim'
on_ft = ['c','verilog','systemverilog','verilog_systemverilog']

###############
# Git
###############
[[plugins]]
repo =  'rhysd/committia.vim'

[[plugins]]
repo ='tpope/vim-fugitive'
depends='committia.vim'
hook_add='''
    set statusline=%F%m%r%h%w\ %=%{fugitive#statusline()}\ \ [%Y,%{&ff}]\ [POS=%04l,%04v][%p%%]\ [LEN=%L]
'''

[[plugins]]
repo =  'gregsexton/gitv'
depends='vim-fugitive'

#[[plugins]]
#repo =  'cohama/agit.vim'

