# 基本は github.com のレポジトリーを指定するだけ
[[plugins]]
repo = 'Shougo/dein.vim'

# git clone 後、実行すべきコマンドがある場合はこんな感じ
[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
elseif executable('gmake')
    let cmd = 'gmake'
else
    let cmd = "echo vimproc: make &&"
    let cmd = cmd.'make'
endif
    let g:dein#plugin.build = cmd
'''
#elseif dein#util#_is_cygwin()
#    let cmd = 'make -f make_cygwin.mak'
#elseif executable('gmake')
#    let cmd = 'gmake'
#else
#    let cmd = 'make'
#endif
#    echo "vimproc: cygwin"
#    echo "vimproc: windows"
#    echo "vimproc: gmake"

#Neomru
[[plugins]]
repo =  'Shougo/neomru.vim'

#Unite
[[plugins]]
repo =  'Shougo/unite.vim'
depends = 'neomru.vim'

#############
# Denite
############
[[plugins]]
repo =  'Shougo/denite.nvim'
depends = 'neomru.vim'
# Key Bind Setting 
hook_add='''
call denite#custom#option('default','direction','top')
call denite#custom#option('default','mode','normal')

"denite/insert モードのときは，C- で移動できるようにする
call denite#custom#map('insert', "<C-j>", '<denite:move_to_next_line>')
call denite#custom#map('insert', "<C-k>", '<denite:move_to_previous_line>')

"tabopen や vsplit のキーバインドを割り当て
call denite#custom#map('insert', "<C-t>", '<denite:do_action:tabopen>')
call denite#custom#map('insert', "<C-v>", '<denite:do_action:vsplit>')
call denite#custom#map('normal', "v", '<denite:do_action:vsplit>')

"jj -> denite/insert を抜けるようにする
call denite#custom#map('insert', 'jj', '<denite:enter_mode:normal>')

nnoremap <Leader>u :Denite file_mru<CR>
nnoremap <Leader>uf :Denite file<CR>
'''

#
#"VimFiler
[[plugins]]
repo =  'Shougo/vimfiler'
#Color Scheme
[[plugins]]
repo =  'sjl/badwolf'
[[plugins]]
repo =  'vim-scripts/twilight'
[[plugins]]
repo =  'vim-scripts/baycomb'
[[plugins]]
repo =  "w0ng/vim-hybrid"
[[plugins]]
repo =  'altercation/vim-colors-solarized'
[[plugins]]
repo = 'tomasr/molokai'
[[plugins]]
repo = 'jpo/vim-railscasts-theme'

#NeoComplete
[[plugins]]
repo =  'Shougo/neocomplete'
[[plugins]]
repo =  'Shougo/neocomplcache'

#Git
[[plugins]]
repo='hotwatermorning/auto-git-diff'
hook_add='''
    let g:auto_git_diff_show_window_at_right=1
'''
[[plugins]]
repo =  'idanarye/vim-merginal'

[[plugins]]
repo =  'cohama/agit.vim'

#Align
[[plugins]]
repo =  'vim-scripts/Align'

#[[plugins]]
#repo =  'changed'
#[[plugins]]
#repo =  'vim-scripts/BlockDiff'
#[[plugins]]
#repo =  'vim-scripts/ifdef.vim'
#
#"VimTex
#[[plugins]]
#repo =  'lervag/vimtex'
#
[[plugins]]
repo =  'LeafCage/foldCC.vim'

[[plugins]]
repo =  'kshenoy/vim-signature'

#
[[plugins]]
repo =  'tpope/vim-surround'
#
#[[plugins]]
#repo =  'thinca/vim-quickrun'
#
#[[plugins]]
#repo =  'wannesm/wmgraphviz.vim'
#
#"Markdown
#[[plugins]]
#repo =  'plasticboy/vim-markdown'
#[[plugins]]
#repo =  'kannokanno/previm'
#[[plugins]]
#repo =  'tyru/open-browser.vim'
#
#"GDB
#"[[plugins]]
#"repo =  'vim-scripts/Conque-GDB'
#
[[plugins]]
repo =  't9md/vim-choosewin'

#"TMUX
[[plugins]]
repo =  'christoomey/vim-tmux-navigator'

#"VimDiff by histogram
#[[plugins]]
#repo =  'lambdalisue/vim-unified-diff'
#[[plugins]]
#repo =  'chrisbra/vim-diff-enhanced'
#
#"Calendar
#[[plugins]]
#repo =  'itchyny/calendar.vim'
#
#"DiffChar
#"[[plugins]]
#"repo =  'vim-scripts/diffchar.vim'
#
