#Table Mode
[[plugins]]
repo =  'dhruvasagar/vim-table-mode'
on_ft=['markdown']

#call unite#custom_default_action('source/bookmark/directory' , 'cd')

#Neomru
[[plugins]]
repo =  'Shougo/neomru.vim'

#Unite
[[plugins]]
repo =  'Shougo/unite.vim'
depends = 'neomru.vim'

#
#"VimFiler
[[plugins]]
repo =  'Shougo/vimfiler'
#[[plugins]]
#repo =  'Shougo/vimshell.vim'
#[[plugins]]
#repo =  't9md/vim-choosewin'
#
#"NeoSnippet
#[[plugins]]
#repo =  'Shougo/neosnippet.vim'
#[[plugins]]
#repo =  'Shougo/neosnippet-snippets'
#
#Git
[[plugins]]
repo =  'tpope/vim-fugitive'

